[settings.npm]
bun = true

[env]
_.file = ".env"

[tools]
age = "latest"
bun = "latest"
marksman = "latest"
"npm:@markdoc/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:fish-lsp" = "latest"
"npm:markdoc-ls" = "latest"
"npm:tombi" = "latest"
"npm:yaml-language-server" = "latest"
sops = "latest"

[tasks.sops-init]
description = "Initialize encrypted sops secrets"
run = "sops decrypt tofu.enc.env > .env"

[tasks.install]
description = "Install dotfiles"
run = "./install.sh"
