# https://writewithharper.com/docs/integrations/helix

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls.linters]
SpellCheck = false
SentenceCapitalization = false

[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls"]
