[settings]
experimental = true
lockfile = true

[settings.npm]
bun = true

[tools]
atuin = "18.8.0"
bat = "0.25.0"
bun = "1.2.19"
eza = "0.23.0"
fastfetch = "2.49.0"
fd = "10.2.0"
fzf = "0.65.1"
github-cli = "2.76.2"
harper-ls = "0.55.0"
helix = "25.07.1"
jq = "1.8.1"
lazygit = "0.54.0"
marksman = "2024-12-18"
node = "24.5.0"
"npm:@charmland/crush" = "0.2.2"
rg = "14.1.1"
starship = "1.23.0"
usage = "2.2.2"
yazi = "25.5.31"
zoxide = "0.9.8"
