[settings]
experimental = true
lockfile = true
yes = true
trusted_config_paths = ["~/Projects", "/workspaces"]

[settings.npm]
bun = true

[settings.python]
uv_venv_auto = true

[tools]
# add on linux laptop: cargo:systemd-lsp and cargo:caligula
atuin = "latest"
bat = "latest"
bun = "latest"
cargo = "latest"
cargo-binstall = "latest"
"cargo:scooter" = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
go = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "latest"
"go:github.com/nametake/golangci-lint-langserver" = "latest"
"go:github.com/wader/jq-lsp" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
harper-ls = "latest"
helix = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyjournal = "latest"
marksman = "latest"
node = "latest"
"npm:@ansible/ansible-language-server" = "latest"
"npm:@charmland/crush" = "latest"
"npm:@markdoc/language-server" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:fish-lsp" = "latest"
"npm:lldb-vscode" = "latest"
"npm:markdoc-ls" = "latest"
"npm:sql-language-server" = "latest"
"npm:tombi" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:ty" = "latest"
rg = "latest"
ruff = "latest"
slsa-verifier = "latest"
starship = "latest"
taplo = "latest"
terraform-ls = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"
zoxide = "latest"
