[settings]
experimental = true
lockfile = true
yes = true
trusted_config_paths = ["~/Projects", "/workspaces"]

[settings.npm]
bun = true

[tools]
atuin = "latest"
bat = "latest"
bun = "latest"
cargo = "latest"
cargo-binstall = "latest"
"cargo:scooter" = "latest"
# cargo:caligula = "latest"
# cargo:systemd-lsp = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
harper-ls = "latest"
helix = "latest"
jj = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyjournal = "latest"
marksman = "latest"
node = "latest"
"npm:@charmland/crush" = "latest"
"npm:@markdoc/language-server" = "latest"
"npm:markdoc-ls" = "latest"
"npm:sql-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
rg = "latest"
slsa-verifier = "latest"
starship = "latest"
usage = "latest"
yazi = "latest"
zoxide = "latest"
