[settings]
experimental = true
lockfile = true

[tools]
atuin = "18.8.0"
bat = "0.25.0"
eza = "0.23.0"
fzf = "0.65.1"
github-cli = "2.76.2"
go = "1.24.5"
"go:github.com/charmbracelet/crush" = "0.2.2"
harper-ls = "0.55.0"
helix = "25.07.1"
lazygit = "0.54.0"
marksman = "2024-12-18"
starship = "1.23.0"
usage = "2.2.2"
yazi = "25.5.31"
zoxide = "0.9.8"
